### ISSUE TITLE
InfluxDB move task list

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamdb.info#473]
- [x] Stop fetching anything from rrd (daily top, etc)
- [x] Stop writing to rrd
- [x] Move SteamSpy data to Influx
- [x] Delete ravenholm.steamdb.info subdomain
- [x] Add scripts to steamdb.info repository
- [x] Move scripts to steamdb.info server
- [x] Enable cron on new server
- [x] Write store queue graphs to Influx
- [x] Write Steam CMs graph to Influx
- [x] Import crawled players data from archived Steam stats pages
